# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 09:48
from __future__ import unicode_literals

import data.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Will be used for internal management. Follow python's variable naming guidelines.", max_length=20, validators=[data.models.validate_for_doc_type_name])),
                ('verbose_name', models.CharField(max_length=120)),
                ('ds_type', models.CharField(choices=[('A', 'API with Structured Data'), ('S', 'API without Structured Data'), ('C', 'No API')], max_length=1)),
                ('miner_class', models.TextField()),
                ('ex_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('es_structure', models.TextField()),
                ('refresh_rate', models.PositiveIntegerField(default=0)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('scrapper_active', models.BooleanField(default=False)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
